INSERT INTO TB_USER(USER_ID, USER_NAME, USER_LOGIN, USER_EMAIL, USER_PASSWORD, USER_BORN_DATE, USER_ACCOUNT_CREATION_DATE, USER_ACCOUNT_LAST_ATT_DATE)
VALUES(2, 'Andre', 'Andre', 'andre@gmail.com', 'Teste2!', '1999-05-12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_USER(USER_ID, USER_NAME, USER_LOGIN, USER_EMAIL, USER_PASSWORD, USER_BORN_DATE, USER_ACCOUNT_CREATION_DATE, USER_ACCOUNT_LAST_ATT_DATE)
VALUES(3, 'Katarina', 'Katarina', 'katari@terra.com.br', '2Katarina.', '2005-09-25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);