INSERT INTO TB_USER(USER_ID, USER_NAME, USER_LOGIN, USER_EMAIL, USER_PASSWORD, USER_BORN_DATE, USER_ACCOUNT_CREATION_DATE, USER_ACCOUNT_LAST_ATT_DATE)
VALUES(1, 'cfcxvndre', 'Asdcnde', 'aszze@gmail.com', 'ddzzz!', '1994-03-18', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_USER(USER_ID, USER_NAME, USER_LOGIN, USER_EMAIL, USER_PASSWORD, USER_BORN_DATE, USER_ACCOUNT_CREATION_DATE, USER_ACCOUNT_LAST_ATT_DATE)
VALUES(2, 'Asfsdfndre', 'Asdfnde', 'asdfe@gmail.com', 'ddfssdf!', '1977-10-14', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_USER(USER_ID, USER_NAME, USER_LOGIN, USER_EMAIL, USER_PASSWORD, USER_BORN_DATE, USER_ACCOUNT_CREATION_DATE, USER_ACCOUNT_LAST_ATT_DATE)
VALUES(3, 'cat', 'cat', 'vic@gmail.com.br', 'sdfsf.', '2001-05-22', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);